list: $/alberich/perfil/models/tipousuario/columns.yaml
modelClass: Alberich\Perfil\Models\TipoUsuario
title: TipoUsuario
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'alberich/perfil/tipousuario/update/:id'
